server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:h2:mem:nutrition_tracker;MODE=PostgreSQL"
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: WARN
    #org.springframework: WARN
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.NutritionTracker: DEBUG
    #org.springframework.jdbc.core.JdbcTemplate: DEBUG
    #org.springframework.jdbc.core.StatementCreatorUtils: TRACE

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
  show-actuator: true