server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/nutrition_tracker"
    username: paf2024
    password: paf2024


logging.level.org:
  springframework.web: DEBUG
  springframework.jps: INFO
  hibernate: INFO

